### ISSUE TITLE
Edited: Crash When Placing Colored Lantern Blocks With New Version of Albedo

### ISSUE THREAD

**Issue by Ecdragonz** [Razzokk/Colored-Lights#12]
Been Testing This. Only using Two Mods Albedo & Colored Lights. Mod crashes whenever i place down a lamp. Here's a pastebin of the crash report and a photo of what MC tells me after.

https://pastebin.com/TLdT1rfA
![crash](https://user-images.githubusercontent.com/45206350/60760415-045c1380-a003-11e9-86cc-42081aefea71.PNG)

If it had been with all Albedo light sources i would have gone to Albedo, but Albedo torches appears to work fine. Really hope you can get back to me soon. 

**Edit:
Its using the May 22nd 2019 Version of Albedo 1.12 labeled "albedo-1.12.2-1.1.0.jar"
Possibly it may be that your mod is making a call to something the new version of Albedo simply doesn't have or was renamed. Hope its an easy fix! I'm going to test the earlier version now.

**Edit2: 
Found the issue. It is the new version of albedo as switching to the "albedo-0.1.3.jar" version fixes the issue. I'm leaving this open for now just for your information as its a massive convenience problem for those who may think the mod is just broken and not take the time to look into it. Have a nice day!

**Comment by Razzokk** [comment]
Fixed in the newest Version: ColoredLights-1.12.2-v1.2.0
