### ISSUE TITLE
Crash using Colored lights on server

### ISSUE THREAD

**Issue by Nomaxice** [Razzokk/Colored-Lights#14]
Using colored lights 1.2.0 for MC 1.12.2, and tried with albedo 1.1.0 and 0.1.3.
Server crashes when finishing up loading the map, preparing the spawn area.
Used to work fine, an automatic reboot happened and then the server just kept crashing for some reason. Tried removing the mod and booting again to remove the blocks from the world, while it booted without colored lights, the server crashed again as soon as I added colored lights back in even with supposedly no blocks left in the world.

Last crash log included, they all are the exact same no matter what.
[crash-2019-07-26_21.23.21-server.txt](https://github.com/Razzokk/Colored-Lights/files/3437269/crash-2019-07-26_21.23.21-server.txt)

Wish you the best of luck on that one, love your mod, and can only imagine how much of a pain it must be to get things to work fine from the little I know.

**Comment by Razzokk** [comment]
So I am currently not at home till monday. But Im gonna take a look at it a soon as i am home.

Sry for the crashing and waiting.

**Comment by Nomaxice** [comment]
Hey there, just wanted to poke in to know if you had any luck figuring this one out?

**Comment by Razzokk** [comment]
I didn't. So I tried to replicate it but without success. I tried to adjust the affected method but I am not sure if it works now.

**Comment by Nomaxice** [comment]
Alright, thanks for the update. Eager to see a new release so we can get colored lights back on our server, thanks for your work and efforts :)

**Comment by Razzokk** [comment]
Should be fixed in the newest version. But you will lose your old ColoredLights Blocks and Items.
