### ISSUE TITLE
Crash exception java.lang.NoClassDefFoundError: elucent/albedo/Albedo

### ISSUE THREAD

**Issue by TheCheshireFox** [Razzokk/Colored-Lights#17]
Hi, i find out one interesting issue with your mod and Albedo.
I don't know should or shouldn't it to be fixed...

Okay, what i figured out.
1. Install Colored Lights and Albedo mods.
2. Create new world, place a lamp.
3. Stop client (didn't try it with dedicated server).
3. Remove Albedo mod.
4. Start client and enter that world.
5. And... as result this [crash report](https://pastebin.com/6Dnuccpp).

**Comment by TheCheshireFox** [comment]
Ow, bad news. Just crash at new world creation.
[Crash report](https://pastebin.com/uLAgvYyp)

**Comment by Razzokk** [comment]
Should be fixed in the neweset version.
