### ISSUE TITLE
Colored Lights causes small phantom-light bugs (in combination with /clone and other movements

### ISSUE THREAD

**Issue by gewenzsko** [Razzokk/Colored-Lights#19]
(ColoredLights1.12.2-v1.2.0 / albedo1.12.2-1.1.0)
Whenever I use the clone command to clone a structure nearby coloredlights, it often creates invisible light-sources that only disappear after a few minutes.
I also have a mod that allows me to smoothly move a structure in vertical and horizontal direction. And often after a movement is done and the structure is at its new place, invisible light appears.

![2020-06-03_22 51 38](https://user-images.githubusercontent.com/66389318/83688314-7c550400-a5ed-11ea-8b7e-9455e3ac9a3b.png)

![2020-06-03_22 51 43](https://user-images.githubusercontent.com/66389318/83688220-562f6400-a5ed-11ea-8445-8ffbdb2079f3.png)

**Comment by Razzokk** [comment]
This is because for "server-light". Albedo does colored lighting but that light will not prevent mobs from spawning so I have to make a kind of hack to solve this problem. So I tell the server that there is a normal minecraft light but the client doesnt know about that. Now if you reload it these phantom things are created. If you go near enough they will disapear. I could add an option for ignoring mob spawn so you have colored light without this problem.

**Comment by gewenzsko** [comment]
No joke. I would pay you just for sending me a coloredlights-mod version without this "hack". I am working with your mod for over a year now and this is my biggest problem. 
I build working theatres with shows and I am using colored light for scene-illumination. Sometimes the whole stage should go black and a few times there are these horrible little lightsources that destroy the whole scene. So I am not using them as a normal lightsource. In my project, the difficulty is set to peaceful and I don't need to prevent mob spawning.


So if you have the time to make a little version without this feature, you would be my hero! Because I am really desperate about this problem.

**Comment by Razzokk** [comment]
Ok. I will add a config option like "preventMobSpawning" you would have to set that to false. After that it could be that you have to again go near the lamp to "clear the phantom light" and then it should stay that way. Im gonna make a patch tomorrow. I hope you can wait until then.

**Comment by gewenzsko** [comment]
Obviously! I can wait! Thank you very much

**Comment by gewenzsko** [comment]
Hey! Just wanted to know if it will take you a few days to finish it  or if the patch will come today?
greetings

**Comment by Razzokk** [comment]
Hi. Well things behave not as I thought they would. Things are getting annoying with Albedo.

**Comment by gewenzsko** [comment]
oh :o I thougt this was just a little thing you added. But okay, just keep my up if you get it fixed! :) Keep up the great work

**Comment by gewenzsko** [comment]
I saw you published a new version a few days ago, were you able to fix the issue?
