### ISSUE TITLE
Special types of entities aren't illuminated while moving (e.g. falling sand)

### ISSUE THREAD

**Issue by gewenzsko** [Razzokk/Colored-Lights#20]
Different kinds of entities are not affected by the colored light when they are not solid/moving.

For example the particles of a breaking block are dark and the animation of falling sand is not illuminated.  
I have a mod that moves structures vertical and horizontal smoothly using entities. When they are moving, they are not affected/illuminated by colored light. 
Only when there is a vanilla lightsource like glowstone nearby, they light up.

The mod behaves kind of like falling sand. So I could imagine if you can fix the problem so that entities like falling sand light up while falling,  it would also fix the problem with my mod.

![EntityBug](https://user-images.githubusercontent.com/66389318/83734988-046bf580-a650-11ea-846a-851447ba1cb9.gif)

Beside those two issues (this one and the phantom lights) I really really love your mod and appreciate that you're answering to this issues and helping us users! Thank you :)

**Comment by Razzokk** [comment]
Thank you for the feedback. I cant really change anything about this since this depends on Albedo for colored lighting. Please report this on their github.

**Comment by gewenzsko** [comment]
Sadly the github of the albedo mod is dead. No one of the authors ever answered to one of the bugs/issues. Do you now anything to change this? Or do you know how I can contact the developers of albedo. I don't think they are active in the albedo github.
Thanks in advance

**Comment by Razzokk** [comment]
Hmm that doesnt sound that good. Well I started reading into code from different colored light mods to get a feeling for how it works, I just started so yeah. It already looks like theres a lot of black magic going on but I keep looking into. I will try and come up with my own colored light core thingy if Im able to.
