### ISSUE TITLE
Game crushes when I open the mod inventory.

### ISSUE THREAD

**Issue by 694895066** [Razzokk/Colored-Lights#21]
Everytime I open the "colored lights" mod inventory in creative mode, the game just automatically shuts down when I click.

I'm using the 1.2.1 version for 1.12.2. Albedo version 1.1.0.

**Comment by Razzokk** [comment]
Do you have a crash log?

**Comment by 694895066** [comment]
> Do you have a crash log?

My apologies, It seems that one of my other mods is the one causing the problem. The 1.2.1 version of Colored Lights mod works normally in vanilla game. Sorry for all the trouble caused by my negligence.

**Comment by Razzokk** [comment]
Don't worry, in that we can close this.
