### ISSUE TITLE
Lights going off after 13/14 blocks of distance

### ISSUE THREAD

**Issue by Alexopfpz** [Razzokk/Colored-Lights#23]
Hi, I noticed that when I go 13/14 blocks away from a lamp, it stops emitting light. Now, I'll need this to be able to be seen from a bit further away so is there any way to increase, if not remove, this distance limit of light-rendering? Yes, I have the Albedo mod installed, obviously. 

Here's a video that shows the issue:

https://user-images.githubusercontent.com/69463088/117451459-dae3da00-af42-11eb-8a23-8e6a736243dd.mp4

**Comment by Razzokk** [comment]
Hi, do you have other lights nearby? There is a limit of how many lights are rendered simultaneously in albedo. Try increasing one or both of these variables in the Albedo.cfg config file: "maxDistance" and "maxLights"

**Comment by Alexopfpz** [comment]
> Hi, do you have other lights nearby? There is a limit of how many lights are rendered simultaneously in albedo. Try increasing one or both of these variables in the Albedo.cfg config file: "maxDistance" and "maxLights"

Hi, yes I did, I went in the mod options and in the config of Albedo and changed both to 200 just to be safe since I didn't know what number would have been better for the situation, by default they were around 40, but still I didn't have those many lamps, still the same problem occurred.

Hold on I'll make you another recording

https://user-images.githubusercontent.com/69463088/117476911-aaf60000-af5d-11eb-8454-dd2e79c15121.mp4

Here you can see when I move that the lights are all flickering but only when I move, if I stand still the ones that are on remain on, but if they were off when I stopped moving they kept staying off.

**Comment by Razzokk** [comment]
Did you try to adjust these settings manually in the config file? It is located in the .minecraft/config folder

**Comment by Alexopfpz** [comment]
> Did you try to adjust these settings manually in the config file? It is located in the .minecraft/config folder

No I'll try thanks

**Comment by Alexopfpz** [comment]
> Did you try to adjust these settings manually in the config file? It is located in the .minecraft/config folder

Seems to be working. Thank you, sorry I thought that doing it in-game was enough. Thank you so much

**Comment by Razzokk** [comment]
No problem, it's weird. It is supossed to work like that, but it seems the config never actually gets saved.
