### ISSUE TITLE
One tiny suggestion

### ISSUE THREAD

**Issue by ServantGirl** [Razzokk/Colored-Lights#3]
So this mod is super cool and I love having more 'hi tech' looking light sources when I'm playing with tech mods. 

The only thing I would suggest is to have the mod use the ore dictionary for dyes, this way if a mod adds its own dye, it can be used in yours.  Its super simple to implement.

**Comment by Razzokk** [comment]
Than you for your suggestion! It was kind of already implemented and I really wanted to release that build but I'm still working on some stuff that I want to include in this build. It will be a content & functionality update.

**Comment by Razzokk** [comment]
It is now fully implemtented in the newest update version 1.1.0!
