### ISSUE TITLE
Oredict

### ISSUE THREAD

**Issue by Fortist** [Razzokk/Colored-Lights#4]
Oredictionary support for creating your colored dyes, which already is a silly addition.

dye[Color] + Glowstone + Redstone = Glowing dye[Color]
Remove Color Dusts or Oredict them
Simple conversion between regular and inverted

**Comment by Razzokk** [comment]
Please read other issues, than you would now that they get oredicted (planned for first release, just forgot to implement it). The update is coming sometime soon, I want to get some stuff done before that. And Colored Dusts (as you can read in its description) get some more functionality in future.
