### ISSUE TITLE
Extra Utilities Conflict/Disabling

### ISSUE THREAD

**Issue by Jstcreepn** [Razzokk/Colored-Lights#5]
Extra Utils GP Becomes Disabled When Clolored Lights Are within 16 blocks Proximity.

**Comment by Razzokk** [comment]
I can't replicate your problem. What is happening, does it stop generating GP or can't you use GP anymore?

**Comment by Jstcreepn** [comment]
When I place the lights and turn one on the GP from extra Utils seems to be
present however there is no transfer of GP between blocks nor to the angel
ring.  As soon as I turn off the light or remove the light GP function
resumes.

**Comment by Jstcreepn** [comment]
I get no crash,  no errors not or otherwise, just Go disruption,  weird.
Lol.

**Comment by Razzokk** [comment]
Thats extremely weird, especially because everything worked fine for me. May be a version thing I'll test that.

**Comment by Razzokk** [comment]
What version are you using?

**Comment by Jstcreepn** [comment]
Extra utils2 1.12-1.7.5 / Colored Lights 1.12.2-v1.1.0 mc1.12.2 Forge
1.12.2-14.23.2.2639

**Comment by Razzokk** [comment]
I'm sorry I can't replicate that problem everything works fine. I tried it with multiple versions (forge and extrautils). I can't fix it for now.

**Comment by Jstcreepn** [comment]
Block ids  where changed during my pack build, seems to be the source of
the issue,  because leaving your ids unchanged and make the change
elsewhere seems to have fixed the issue.  Odd to say the least.  Thanks
anyhow.

**Comment by Jstcreepn** [comment]
I'm not certian what change you made however i've installed your update in the mod pack that was giving me issue useing the same changes i made the first time. Now the lights no longer cause GP to fail. THANKS!!!

**Comment by Razzokk** [comment]
Sounds good ^^

Jstcreepn <notifications@github.com> schrieb am Do., 29. März 2018, 00:19:
