### ISSUE TITLE
Exception thrown when trying to break Grinder.

### ISSUE THREAD

**Issue by Wolf-Valecos** [Razzokk/Colored-Lights#6]
I get the following exception when using this on my server whenever I try to break the grinder or use it. It causes the grinder to only be destroy-able by explosions.

java.lang.NoSuchMethodError: coloredlights.tileentity.TileEntityGrinder.isGrinding(Lnet/minecraft/inventory/IInventory;)Z at coloredlights.block.BlockGrinder.func_176221_a(BlockGrinder.java:103)

**Comment by Razzokk** [comment]
Fixed in the newest Version: ColoredLights-1.12.2-v1.2.0
