### ISSUE TITLE
Crash when launching a server with a modpack

### ISSUE THREAD

**Issue by C7007** [Razzokk/Colored-Lights#9]
Well, I'm on a server with other mods and I can't craft or find the grinder in both creative and survival modes.
Here are my mods
-Quark
-Albedo
-Weiss Albedo
-Regeneration
-Colored Lights
-CHisel
-Colored Waters
-Compact Machines
-Colored Redstones

**Comment by Razzokk** [comment]
Are you using the latest version? Is the mod even loaded?

**Comment by C7007** [comment]
Well it was not up to date, sorry for bothering you

**Comment by C7007** [comment]
Sorry to bother you again. My server crashes when I try to launch it. I've tried several versions of the mod, including the latest

https://cdn.discordapp.com/attachments/234727722037936138/569447163906752542/crash-2019-04-21_10.59.07-server.txt

**Comment by Razzokk** [comment]
Oh damn. Yeah I have to throw out a fix, the newest version seems to not be fully compatible with servers due to keybindings.

**Comment by C7007** [comment]
so, is there a way to temporarily fix it?

**Comment by Razzokk** [comment]
Yes, in fact it is already fixed in the current development build. Problem is that there are many things I have to finish before a release.

**Comment by Razzokk** [comment]
Fixed in the newest Version: ColoredLights-1.12.2-v1.2.0
